#!/bin/bash

#Copyright (C) 2020 Hesham Banafa
# 19 Aug 2020 - H.B

#This file is part of stonks.

#    stonks is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    any later version.
#
#    stonks is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with stonks.  If not, see <https://www.gnu.org/licenses/>.

#read arg and get info from mubasher
raw=$(curl -s "https://english.mubasher.info/markets/TDWL/stocks/$1" | \
	html2text2 | \
	sed -n '/Last update:/,$p' | \
	sed -n '/Stock Statistics/q;p')
mkdir -p raw
echo "$raw" > "raw/$1"
