#!/bin/bash

#Copyright (C) 2020 Hesham Banafa

#This file is part of stonks.

#    stonks is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    any later version.
#
#    stonks is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with stonks.  If not, see <https://www.gnu.org/licenses/>.

#cli interface to track TASI profolio
# 19 Aug 2020 - H.B

version=0.1-alpha
version_msg="stonks $version"
echo "$version_msg"

#check jq
if ! command -v jq &> /dev/null
then
	echo "Can't find jq (json)"
	exit 1
fi
