#!/bin/bash

#Copyright (C) 2020 Hesham Banafa
# 20 Aug 2020 - H.B.

#This file is part of stonks.

#    stonks is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    any later version.
#
#    stonks is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with stonks.  If not, see <https://www.gnu.org/licenses/>.

#go throgh all stocks in data dir and update "current" json value.
if [ -d data ]
then

	stock_files=$(ls data)
	for file in $stock_files
	do
	code=$(echo $file | sed 's/.json//g')
	./getinfo $code && echo "updated $code"
	current=$(./readprice $code)
	if [ -z current ]
	then
		current="null"
	fi
	new_json=$(jq ".current = $current" data/$file)
	echo $new_json | jq . > data/$file
	done
else
	echo "No current holdings"
	exit 1
fi
